mostafa:

  orchestration:
    save: False
    detection: True
    recognition: True
    tracking: True

  kafka:
    produce: True
    server:
      bootstrap.servers: localhost:9092
    topic: "SourceKafkaTopic.Source"

  stream:
    # 0: rtsp://192.168.1.103:554/user=admin&password=&channel=1&stream=0.sdp?real_stream--rtp-caching=800
    # 1: rtsp://192.168.1.103:554/user=admin&password=&channel=2&stream=0.sdp?real_stream--rtp-caching=800
    0: /mnt/storage/projects/Aktar/Aktar-develop/videos/home-mostafa/cam0.avi
    1: /mnt/storage/projects/Aktar/Aktar-develop/videos/home-mostafa/cam1.avi

  detection:
    weights: aktarai/detection/weights/yolov8s-pose.pt

  recognition:
    device: gpu
    weights: aktarai/recognition/weights/osnet_x0_25_msmt17.onnx
    input_size: [128, 256]

  pose_estimation:
    0: demo/home-mostafa/cam1.json
    1: demo/home-mostafa/cam2.json

  tracking:
    mapping:
      0:
        calibration_file: /mnt/storage/projects/Aktar/Mapping/data/IR-opencv/calibration.yaml
        image_points: /mnt/storage/projects/Aktar/Mapping/data/home-mostafa/calibration/1_img_pnts.npy
        physical_points: /mnt/storage/projects/Aktar/Mapping/data/home-mostafa/calibration/1_phys_pnts.npy
      1:
        calibration_file: /mnt/storage/projects/Aktar/Mapping/data/IR-opencv/calibration.yaml
        image_points: /mnt/storage/projects/Aktar/Mapping/data/home-mostafa/calibration/2_img_pnts.npy
        physical_points: /mnt/storage/projects/Aktar/Mapping/data/home-mostafa/calibration/2_phys_pnts.npy

  warning_zones:
    0: {"x1": 3.0, "z1": 3.5, "x2": 4.9, "z2": 6.35}
