dt:
  pose_estimation:
    vid1: /mnt/storage/projects/ultralytics/parand-yolov8l/parand-122.json
    vid2: /mnt/storage/projects/ultralytics/parand-yolov8l/parand-123.json
    vid3: /mnt/storage/projects/ultralytics/parand-yolov8l/parand-124.json
    vid4: /mnt/storage/projects/ultralytics/parand-yolov8l/parand-125.json

  engine:
    pose_data: modules/Aktar_AI/DTwin/assets/pose_data.json

    mapping:
      0:
        calibration_file: /mnt/storage/projects/Aktar/Mapping/data/parand-type3/calibration.yaml
        image_points: /mnt/storage/projects/Aktar/Mapping/data/parand/calibration/122_img_pnts.npy
        physical_points: /mnt/storage/projects/Aktar/Mapping/data/parand/calibration/122_phys_pnts.npy
      1:
        calibration_file: /mnt/storage/projects/Aktar/Mapping/data/parand-type3/calibration.yaml
        image_points: /mnt/storage/projects/Aktar/Mapping/data/parand/calibration/123_img_pnts.npy
        physical_points: /mnt/storage/projects/Aktar/Mapping/data/parand/calibration/123_phys_pnts.npy
      2:
        calibration_file: /mnt/storage/projects/Aktar/Mapping/data/parand-type3/calibration.yaml
        image_points: /mnt/storage/projects/Aktar/Mapping/data/parand/calibration/124_img_pnts.npy
        physical_points: /mnt/storage/projects/Aktar/Mapping/data/parand/calibration/124_phys_pnts.npy
      3:
        calibration_file: /mnt/storage/projects/Aktar/Mapping/data/parand-type3/calibration.yaml
        image_points: /mnt/storage/projects/Aktar/Mapping/data/parand/calibration/125_img_pnts.npy
        physical_points: /mnt/storage/projects/Aktar/Mapping/data/parand/calibration/125_phys_pnts.npy

    warning_zones:
      0: {"x1": 3.0, "z1": 4.0, "x2": 5.3, "z2": 5.85}

  video:
    0: /mnt/storage/projects/Aktar/Mapping/data/parand/video/out_0.avi
    1: /mnt/storage/projects/Aktar/Mapping/data/parand/video/out_1.avi
    2: /mnt/storage/projects/Aktar/Mapping/data/parand/video/out_2.avi
    3: /mnt/storage/projects/Aktar/Mapping/data/parand/video/out_3.avi

  kafka:
    server:
      bootstrap.servers: localhost:9092
    topic: "SourceKafkaTopic.Source"
